[tool.poetry]
name = "geometry"
version = "0.1.0"
description = "geoemtry 2D, classes and tools"
authors = ["matthcol <matthcol@example.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^3.0.3"
numpy = "^2.4.6"


[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"

[tool.pytest.ini_options]
testpaths    = ["tests"]
pythonpath   = ["."]   
addopts      = "-v"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
